// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasDiscoteca.API.Data;

#nullable disable

namespace ReservasDiscotema.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115085738_V3_SistemaDeCompras")]
    partial class V3_SistemaDeCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Boliche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boliches");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolicheId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolicheId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.CompraManilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("ManillaTipoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioEnElMomento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ManillaTipoId");

                    b.ToTable("CompraManillas");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.ManillaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolicheId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolicheId");

                    b.ToTable("ManillaTipos");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BolicheId")
                        .HasColumnType("int");

                    b.Property<int?>("CompraId")
                        .HasColumnType("int");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("NombreONumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioReserva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BolicheId");

                    b.HasIndex("CompraId")
                        .IsUnique()
                        .HasFilter("[CompraId] IS NOT NULL");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Compra", b =>
                {
                    b.HasOne("ReservasDiscoteca.API.Entities.Boliche", "Boliche")
                        .WithMany()
                        .HasForeignKey("BolicheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservasDiscoteca.API.Entities.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boliche");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.CompraManilla", b =>
                {
                    b.HasOne("ReservasDiscoteca.API.Entities.Compra", "Compra")
                        .WithMany("ManillasCompradas")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasDiscoteca.API.Entities.ManillaTipo", "ManillaTipo")
                        .WithMany()
                        .HasForeignKey("ManillaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("ManillaTipo");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.ManillaTipo", b =>
                {
                    b.HasOne("ReservasDiscoteca.API.Entities.Boliche", "Boliche")
                        .WithMany("ManillaTipos")
                        .HasForeignKey("BolicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boliche");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Mesa", b =>
                {
                    b.HasOne("ReservasDiscoteca.API.Entities.Boliche", "Boliche")
                        .WithMany("Mesas")
                        .HasForeignKey("BolicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasDiscoteca.API.Entities.Compra", "Compra")
                        .WithOne("MesaReservada")
                        .HasForeignKey("ReservasDiscoteca.API.Entities.Mesa", "CompraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Boliche");

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Boliche", b =>
                {
                    b.Navigation("ManillaTipos");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Compra", b =>
                {
                    b.Navigation("ManillasCompradas");

                    b.Navigation("MesaReservada")
                        .IsRequired();
                });

            modelBuilder.Entity("ReservasDiscoteca.API.Entities.Usuario", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
